#ifndef PRISONERDILEMMA_GLOBAL_H
#define PRISONERDILEMMA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PRISONERDILEMMA_LIBRARY)
#  define PRISONERDILEMMASHARED_EXPORT Q_DECL_EXPORT
#else
#  define PRISONERDILEMMASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PRISONERDILEMMA_GLOBAL_H
