#ifndef TRAVELINGSALESMAN_GLOBAL_H
#define TRAVELINGSALESMAN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRAVELINGSALESMAN_LIBRARY)
#  define TRAVELINGSALESMANSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRAVELINGSALESMANSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRAVELINGSALESMAN_GLOBAL_H
