#ifndef QUADRATICEQUATIONSOLVING_GLOBAL_H
#define QUADRATICEQUATIONSOLVING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QUADRATICEQUATIONSOLVING_LIBRARY)
#  define QUADRATICEQUATIONSOLVINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QUADRATICEQUATIONSOLVINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QUADRATICEQUATIONSOLVING_GLOBAL_H
