#ifndef WORDMATCHINGPROBLEM_GLOBAL_H
#define WORDMATCHINGPROBLEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WORDMATCHINGPROBLEM_LIBRARY)
#  define WORDMATCHINGPROBLEMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WORDMATCHINGPROBLEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WORDMATCHINGPROBLEM_GLOBAL_H
